name: iOS starter workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest
    
    strategy:
        matrix:
          destination: ["platform=iOS Simulator,OS=14.0,name=iPhone 11 Pro"]

    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Simulator
        run: xcrun instruments -w "iPhone 11 Pro (14.0) [" || true
      - name: Build
        run: |
          xcodebuild clean build -project Football_API.xcodeproj -scheme Football_API -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project GHFollowers.xcodeproj -scheme GHFollowersTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
