name: iOS starter workflow

on: [push]

jobs:
  run_tests:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.app && /usr/bin/xcodebuild -version
    - name: Preinstall
      run: xcversion simulators --install='iOS 15.0'
    - name: Run unit tests
      run: xcodebuild test -scheme Football_API -project Football_API.xcodeproj -destination 'platform=iOS Simulator,name=iPhone 12,OS=15.0' clean build test
