name: iOS starter workflow

on: [push]

jobs:
  run_tests:
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v1
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode_13.2.app && /usr/bin/xcodebuild -version
    - name: Run unit tests
      run: xcodebuild test -scheme Football_API -project Football_API.xcodeproj -destination 'id=DFB14113-4697-4E2D-AD3F-B4FBA4B62969' clean build test
